web:
  image: asermax/node-yarn
  links:
    - db
  ports:
    - "8000:8000"
  volumes:
    - .:/opt/app
    - plus_dependencies:/opt/app/node_modules
  working_dir: /opt/app
  command: yarn run start
  environment:
    MONGO_URL: mongodb://db:27017/plus
db:
  image: mongo:latest
  ports:
    - "27017:27017"

